<?php

namespace AppBundle\Repository;

/**
 * ActionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActionRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByCropCycle($id)
    {
        $qb = $this->createQueryBuilder('a');

        $qb->join('a.cropCycle', 'cropCycle')
            ->addSelect('cropCycle')
            ->where('cropCycle.id = :id')
            ->setParameter('id', $id)
            ->orderBy('a.endDatetime');

        return $qb
            ->getQuery()
            ->getResult();
    }

    public function findByInterventionCategory($id)
    {
        $qb = $this->createQueryBuilder('a');

        $qb->join('a.intervention', 'int')
            ->addSelect('int')
            ->join('int.interventionCategory', 'cat')
            ->addSelect('cat')
            ->where('cat.id = :id')
            ->setParameter('id', $id);

        return $qb
            ->getQuery()
            ->getResult();
    }

    public function findByCrop($id)
    {
        $qb = $this->createQueryBuilder('a');

        $qb->join('a.cropCycle', 'cycle')
            ->addSelect('cycle')
            ->join('cycle.crops', 'crops')
            ->addSelect('crops')
            ->where('crops.id = :id')
            ->setParameter('id', $id);

        return $qb
            ->getQuery()
            ->getResult();
    }
}
