<?php

namespace AppBundle\Repository;

/**
 * ActionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActionRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByCropCycle($id)
    {
        $qb = $this->createQueryBuilder('a');

        $qb->join('a.cropCycle', 'cropCycle')
            ->addSelect('cropCycle')
            ->where('cropCycle.id = :id')
            ->setParameter('id', $id);

        return $qb
            ->getQuery()
            ->getResult();
    }
}
