<?php

namespace AppBundle\Repository;

/**
 * CropCycleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CropCycleRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByCropAndCampaign($crop, $year, $farm)
    {

        $yearStart =   \DateTime::createFromFormat("Y-m-d H:i:s",$year."-01-01 00:00:00");
        $yearEnd =   \DateTime::createFromFormat("Y-m-d H:i:s",$year."-12-31 23:59:59");

        $qb = $this->createQueryBuilder('c');

        $qb->join('c.crops','crops')
            ->addSelect('crops')
            ->join('c.plot','p')
            ->addSelect('p')
            ->join('p.farm','farm')
            ->addSelect('farm')
            ->where('crops.id = :crop AND farm.id =:farm AND c.startDatetime BETWEEN :yearStart AND :yearEnd')
            ->setParameter('crop', $crop)
            ->setParameter('farm', $farm)
            ->setParameter('yearStart', $yearStart)
            ->setParameter('yearEnd', $yearEnd)
            ->orWhere('crops.id = :crop AND farm.id =:farm  AND c.endDatetime BETWEEN :yearStart AND :yearEnd')
            ->setParameter('crop', $crop)
            ->setParameter('farm', $farm)
            ->setParameter('yearStart', $yearStart)
            ->setParameter('yearEnd', $yearEnd)
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }

    // Create findByPlotAndCampaign()
}
