<?php

namespace AppBundle\Repository;

/**
 * CropCyleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CropCyleRepository extends \Doctrine\ORM\EntityRepository
{
}
