<?php

namespace AppBundle\Repository;

/**
 * FarmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FarmRepository extends \Doctrine\ORM\EntityRepository
{
}
