<?php

namespace AppBundle\Repository;

/**
 * FarmSpecialityMvtRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FarmSpecialityMvtRepository extends \Doctrine\ORM\EntityRepository
{
}
