<?php

namespace AppBundle\Repository;

/**
 * FarmSpecialityMvtRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FarmSpecialityMvtRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllByFarmSpeciality ($id)
    {
        $qb = $this->createQueryBuilder('m');

        $qb->where('m.speciality = :speciality')
            ->setParameter('speciality', $id)
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
}
