<?php

namespace AppBundle\Repository;

/**
 * FarmSpecialityMvtCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FarmSpecialityMvtCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
