<?php

namespace AppBundle\Repository;

/**
 * FarmFertilizerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FarmFertilizerRepository extends \Doctrine\ORM\EntityRepository
{
}
