<?php

namespace AppBundle\Repository;

/**
 * FarmFertilizerMvtCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FarmFertilizerMvtCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
