<?php

namespace AppBundle\Repository;

/**
 * FertilizerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FertilizerRepository extends \Doctrine\ORM\EntityRepository
{
}
