<?php

namespace AppBundle\Repository;

/**
 * FertilizersPriceUpdateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FertilizersPriceUpdateRepository extends \Doctrine\ORM\EntityRepository
{
}
