<?php

namespace AppBundle\Repository;

/**
 * FertilizerPriceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FertilizerPriceRepository extends \Doctrine\ORM\EntityRepository
{
}
