<?php

namespace AppBundle\Repository;

/**
 * HarvestProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HarvestProductRepository extends \Doctrine\ORM\EntityRepository
{
}
