<?php

namespace AppBundle\Repository;

/**
 * ImplementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImplementRepository extends \Doctrine\ORM\EntityRepository
{
    public function qbFindAllForCurrentFarm ($id)
    {
        $qb = $this->createQueryBuilder('i');

        $qb->where('i.farm = :farm')
            ->setParameter('farm', $id)
        ;

        return $qb;
    }

    public function findAllForCurrentFarm ($id)
    {
        $qb = $this->qbFindAllForCurrentFarm($id);

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
}
