<?php

namespace AppBundle\Repository;

/**
 * ImplementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImplementRepository extends \Doctrine\ORM\EntityRepository
{
}
