<?php

namespace AppBundle\Repository;

/**
 * PlotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlotRepository extends \Doctrine\ORM\EntityRepository
{
}
