<?php

namespace AppBundle\Repository;

/**
 * SpecialityUsageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpecialityUsageRepository extends \Doctrine\ORM\EntityRepository
{
}
