<?php

namespace AppBundle\Repository;

/**
 * SubstanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubstanceRepository extends \Doctrine\ORM\EntityRepository
{
}
