<?php

namespace AppBundle\Repository;

/**
 * TractorBrandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TractorModelRepository extends \Doctrine\ORM\EntityRepository
{
}
