<?php

namespace AppBundle\Repository;

/**
 * TractorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TractorRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllForCurrentFarm ($id)
    {
        $qb = $this->createQueryBuilder('t');

        $qb->join('t.farm','f')
            ->addSelect('f')
            ->where('f.id = :farm')
            ->setParameter('farm', $id)
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
}
